# Generated by Django 2.1.2 on 2018-10-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promotionNum', models.CharField(max_length=5)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.Products')),
            ],
        ),
    ]
