# Generated by Django 2.1.2 on 2018-11-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressee',
            new_name='address',
        ),
    ]
