# Generated by Django 2.1.2 on 2018-11-10 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0004_remove_promotion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='expireDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expire Date Data'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
