# Generated by Django 2.1.2 on 2018-11-10 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0005_auto_20181111_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='expireDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expire Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
    ]
