# Generated by Django 2.1.2 on 2018-11-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0007_auto_20181111_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
