# Generated by Django 2.1.2 on 2018-11-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0008_auto_20181111_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingCart.Products'),
        ),
    ]
