# Generated by Django 2.1.2 on 2018-11-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0011_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('add_logentry', 'Can add log entry'), ('change_logentry', 'Can change log entry'), ('delete_logentry', 'Can delete log entry'), ('view_logentry', 'Can view log entry'), ('add_group', 'Can add group'), ('change_group', 'Can change group'), ('delete_group', 'Can delete group'), ('view_group', 'Can view group'), ('add_permission\tCan', 'add permission'), ('change_permission', 'Can change permission'), ('delete_permission', 'Can delete permission'), ('view_permission', 'Can view permission'), ('add_contenttype', 'Can add content type'), ('change_contenttype', 'Can change content type'), ('delete_contenttype', 'Can delete content type'), ('view_contenttype', 'Can view content type'), ('add_session', 'Can add session'), ('change_session\t', 'Can change session'), ('delete_session', 'Can delete session'), ('view_session', 'Can view session'), ('add_products', 'Can add products'), ('change_products', 'Can change products'), ('delete_products', 'Can delete products'), ('view_products', 'Can view products'), ('add_address', 'Can add address'), ('change_address\t', 'Can change address'), ('delete_address', '\tCan delete address'), ('view_address', 'Can view address'), ('add_cart', 'Can add cart'), ('change_cart', 'Can change cart'), ('delete_cart', 'Can delete cart'), ('view_car', 'Can view cart'), ('add_orders', 'Can add orders'), ('change_orders', 'Can change orders'), ('delete_orders', 'Can delete orders'), ('view_orders', 'Can view orders'), ('add_promotion', 'Can add promotion'), ('change_promotion', 'Can change promotion'), ('delete_promotion', 'Can delete promotion'), ('view_promotion\tCan', 'view promotion')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
