# Generated by Django 2.1.2 on 2018-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0013_auto_20181114_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotionNum',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
