# Generated by Django 2.1.2 on 2018-11-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0016_auto_20181115_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='totalPrice',
        ),
    ]
