# Generated by Django 2.1.2 on 2018-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0018_auto_20181115_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
