# Generated by Django 2.1.2 on 2018-12-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0023_auto_20181121_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='../static/img/'),
        ),
    ]
