# Generated by Django 2.1.2 on 2018-12-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0024_auto_20181209_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='productID',
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='static/img/product/'),
        ),
    ]
